// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewDotnetProject.Data;

#nullable disable

namespace newDotnetProject.Migrations
{
    [DbContext(typeof(CollegeDBContext))]
    [Migration("20241219053147_StudentCreate")]
    partial class StudentCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NewDotnetProject.Data.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("collegeAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("collegeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Colleges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            collegeAddress = "ECE Department",
                            collegeName = "ECE"
                        },
                        new
                        {
                            Id = 2,
                            collegeAddress = "CSE Department",
                            collegeName = "CSE"
                        });
                });

            modelBuilder.Entity("NewDotnetProject.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("studentAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("studentEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DOB = new DateTime(2022, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            studentAddress = "India",
                            studentEmail = "venkat@gmail.com",
                            studentName = "Venkat"
                        },
                        new
                        {
                            Id = 2,
                            DOB = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            studentAddress = "India",
                            studentEmail = "nehanth@gmail.com",
                            studentName = "Nehanth"
                        });
                });

            modelBuilder.Entity("NewDotnetProject.Data.Student", b =>
                {
                    b.HasOne("NewDotnetProject.Data.College", "College")
                        .WithMany("Students")
                        .HasForeignKey("CollegeId")
                        .HasConstraintName("FK_Students_College");

                    b.Navigation("College");
                });

            modelBuilder.Entity("NewDotnetProject.Data.College", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
